export enum ConsumptionPeriodEnum {
  DAY = 'day',
  WEEK = 'week',
  MONTH = 'month',
  YEAR = 'year',
}

export enum EmissionsFactorEnum {
  HOUSING_ELECTRICITY = 'housingElectricity',
  HOUSING_NATURALGAS = 'housingNaturalGas',
  HOUSING_FUEL_OIL = 'housingFuelOil',
  HOUSING_LPG = 'housingLPG',
  HOUSING_WASTE = 'housingWaste',
  HOUSING_WATER = 'housingWater',
  TRAVEL_VEHICLE = 'travelVehicle',
  TRAVEL_BUS = 'travelBus',
  TRAVEL_METRO = 'travelMetro',
  TRAVEL_TAXI = 'travelTaxi',
  TRAVEL_RAIL = 'travelRail',
  TRAVEL_FLYING = 'travelFlying',
  FOOD_RED_MEAT = 'foodRedMeat',
  FOOD_WHITE_MEAT = 'foodWhiteMeat',
  FOOD_DAIRY = 'foodDairy',
  FOOD_CEREALS = 'foodCereals',
  FOOD_VEGETABLES = 'foodVegetables',
  FOOD_FRUIT = 'foodFruit',
  FOOD_OILS = 'foodOils',
  FOOD_SNACKS = 'foodSnacks',
  FOOD_DRINKS = 'foodDrinks',
  PRODUCTS_ELECTRICAL = 'ProductsElectrical',
  PRODUCTS_HOUSEHOLD = 'ProductsHousehold',
  PRODUCTS_CLOTHES = 'ProductsClothes',
  PRODUCTS_MEDICAL = 'ProductsMedical',
  PRODUCTS_RECREATIONAL = 'ProductsRecreational',
  PRODUCTS_OTHER = 'ProductsOther',
  SERVICES_HEALTH = 'servicesHealth',
  SERVICES_FINANCE = 'servicesFinance',
  SERVICES_RECREATION = 'servicesRecreation',
  SERVICES_EDUCATION = 'servicesEducation',
  SERVICES_VEHICLE = 'servicesVehicle',
  SERVICES_COMMUNICATIONS = 'servicesCommunications',
  SERVICES_OTHER = 'servicesOther',
}
